#!/bin/bash

sudo apt-get install x-terminal-emulator
x-terminal-emulator -e ./broker/broker 0

while read -n1 -r -p "choose [p] to generate another producer, or [c] to generate another consumer" && [[ $REPLY != q ]]; do
    echo
    case $REPLY in
        p) x-terminal-emulator -e ./producer/producer 0;;
        c) x-terminal-emulator -e ./consumer/consumer 0;;
        *) echo "What?";;
    esac
done