#!/bin/bash

x-terminal-emulator -e ./b 0
sleep 1
x-terminal-emulator -e ./c 0
sleep 1
x-terminal-emulator -e ./p 0
sleep 1


while read -r -p "Choose:`echo $'\n-'`[p]To create a producer`echo $'\n-'`[c]To create a consumer`echo $'\n-'`[cn]To create a consumer with a given port`echo $'\n-'`[q]Quit`echo $'\n-'`> " && [[ $REPLY != q ]]; do
    echo
    case $REPLY in
        p) x-terminal-emulator -e ./p 0
	   ;;
        c) x-terminal-emulator -e ./c 0
	   ;;
	cn) read -r -p "Port number: "
            x-terminal-emulator -e ./c 2 $REPLY
	    ;;
        *) echo "What?";;
    esac
done